---
apiVersion: v1
kind: Service
metadata:
  name: sysdigcloud-elasticsearch
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: sysdigcloud
    role: elasticsearch
spec:
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - port: 9200
      name: api
    - port: 9300
      name: transport-protocol
  selector:
    app: sysdigcloud
    role: elasticsearch
