---
apiVersion: v1
kind: Service
metadata:
  name: sysdigcloud-anchore-feeds
  labels:
    app: sysdigcloud
    role: anchore-feeds
spec:
  type: ClusterIP
  ports:
  - name: feeds-api
    port: 8448
    protocol: TCP
    targetPort: 8448
  selector:
    app: sysdigcloud
    role: anchore-feeds
