apiVersion: v1
kind: ConfigMap
metadata:
  name: sysdigcloud-anchore-core
  labels:
    app: sysdigcloud
    role: anchore-core
data:
  config.yaml: |
    service_dir: /anchore_service_config
    tmp_dir: "/tmp"
    allow_awsecr_iam_auto: false
    cleanup_images: true
    log_level: INFO
    host_id: ${ANCHORE_POD_NAME}
    internal_ssl_verify: false
    metrics:
      enabled: false
    feeds:
      selective_sync:
        enabled: True
        feeds:
          vulnerabilities: True
          nvd: True
          packages: False
    default_admin_password: ${ANCHORE_ADMIN_PASSWORD}
    default_admin_email: 'admin@myemail.com'
    credentials:
      database:
        db_connect: "postgresql+pg8000://${ANCHORE_DB_USER}:${ANCHORE_DB_PASSWORD}@${ANCHORE_DB_ENDPOINT}/${ANCHORE_DB}"
        db_connect_args:
          timeout: 120
          ssl: false
        db_pool_size: 50
        db_pool_max_overflow: 70
    services:
      apiext:
        enabled: True
        require_auth: True
        endpoint_hostname: sysdigcloud-anchore-core
        listen: '0.0.0.0'
        port: 8228
      kubernetes_webhook:
        enabled: True
        require_auth: False
        endpoint_hostname: sysdigcloud-anchore-core
        listen: '0.0.0.0'
        port: 8338
      catalog:
        enabled: True
        require_auth: True
        endpoint_hostname: sysdigcloud-anchore-core
        listen: '0.0.0.0'
        port: 8082
        use_db: True
        cycle_timer_seconds: 1
        cycle_timers:
          analyzer_queue: 1
          feed_sync: 14400
          image_watcher: 3600
          notifications: 30
          policy_bundle_sync: 300
          policy_eval: 3600
          service_watcher: 15

        event_log:
          notification:
            enabled: false
            level:
              - error
        archive:
          compression:
            enabled: true
            min_size_kbytes: 100
          storage_driver:
            name: db
            config: {}
      simplequeue:
        enabled: True
        require_auth: True
        endpoint_hostname: sysdigcloud-anchore-core
        listen: '0.0.0.0'
        port: 8083
      policy_engine:
        enabled: True
        require_auth: True
        endpoint_hostname: sysdigcloud-anchore-core
        listen: '0.0.0.0'
        port: 8087
        catalog_client_conn_timeout: 30
        catalog_client_read_timeout: 3600