---
apiVersion: v1
kind: Service
metadata:
  name: sysdigcloud-api
  labels:
    app: sysdigcloud
    role: api
spec:
  clusterIP: None
  ports:
    - port: 443
      name: secure-api
      targetPort: 443
    - port: 8080
      name: api
      targetPort: 8080
  selector:
    app: sysdigcloud
    role: api
