apiVersion: v1
kind: Service
metadata:
  name: sysdigcloud-scanning-api
  labels:
    app: sysdigcloud
    role: scanning-api
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
  selector:
    app: sysdigcloud
    role: scanning-api
