apiVersion: v1
kind: Service
metadata:
  name: sysdigcloud-postgresql
  labels:
    app: sysdigcloud
    role: postgresql
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: sysdigcloud
    role: postgresql
